// Wallet addresses for deposits - INVESTMENT HOLDINGS, LLC official wallets
export const walletAddresses = {
  BTC: {
    address: "bc1qwkj0vpurr8kq7h40k2hew75k3366y6r8j6xajj",
    name: "Bitcoin",
    symbol: "BTC",
    network: "Bitcoin Network",
    icon: "bitcoin",
    color: "orange",
    minDeposit: 0.0001,
    confirmations: 3,
  },
  ETH: {
    address: "0xF8b9FCA44267D89653355a246Ccf918831e57a0c",
    name: "Ethereum",
    symbol: "ETH",
    network: "Ethereum Network",
    icon: "ethereum",
    color: "indigo",
    minDeposit: 0.001,
    confirmations: 12,
  },
  USDC: {
    address: "0xF8b9FCA44267D89653355a246Ccf918831e57a0c",
    name: "USD Coin",
    symbol: "USDC",
    network: "Base Network",
    icon: "usdc",
    color: "blue",
    minDeposit: 10,
    confirmations: 12,
  },
  USDT: {
    address: "0xF8b9FCA44267D89653355a246Ccf918831e57a0c",
    name: "Tether",
    symbol: "USDT",
    network: "ERC-20 (Ethereum)",
    icon: "usdt",
    color: "emerald",
    minDeposit: 10,
    confirmations: 12,
  },
  LTC: {
    address: "Lh62s2tFensTcioux3biiBJeJqi73bPXPN",
    name: "Litecoin",
    symbol: "LTC",
    network: "Litecoin Network",
    icon: "litecoin",
    color: "slate",
    minDeposit: 0.01,
    confirmations: 6,
  },
  DOGE: {
    address: "DRrcTS3wzBJ5GfMKZH5DE8LjGu7ouow167",
    name: "Dogecoin",
    symbol: "DOGE",
    network: "Dogecoin Network",
    icon: "dogecoin",
    color: "amber",
    minDeposit: 10,
    confirmations: 6,
  },
}

export type CryptoKey = keyof typeof walletAddresses
